### ISSUE TITLE
🌟 Feature: Decimal numbers

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#13]
Hi everyone 👋,
I could use some help implementing a decimal functionality that allows the user to calculate decimal numbers.
**Example:** 12.5 - 3.75

Thank you kindly 🙏
Best regards
NH

**Comment by Vayras** [comment]
@N3v1 I would like to work on this issue can you please assign me this issue?

**Comment by N3v1** [comment]
@Vayras Here you go. Thank you very much

Best regards
NH

**Comment by N3v1** [comment]
Hi @Vayras, 
could you kindly share an update regarding the status of your decimal implementation? 
It would be greatly appreciated.

Thank you kindly 🙏
Best regards
NH
