### ISSUE TITLE
🌟 Feature: Adding keyboard input

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#16]
Hi everyone 👋,
I need assistance with adding the ability to input numbers and mathematical operators such as addition, subtraction, multiplication, and division with the keyboard.

Thank you kindly
Best regards
NH

**Comment by ify47** [comment]
Hey there!, could i contribute to this issue?, i got a fix for you!

**Comment by N3v1** [comment]
Sure @ify47
