### ISSUE TITLE
🟡 Adapt website for iPhones and other mobile devices

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#17]
Hi everyone 👋,
I could use some help to adapt the calculator for iPhones and other mobile devices. 

---

<img width="200" src="https://github.com/N3v1/Calculator/assets/129311622/f7063f8c-27c6-4a71-aa5b-0abfd0df0732"></a>
<img width="500" src="https://github.com/N3v1/Calculator/assets/129311622/9c7cfa5c-dd81-4611-87ab-d4884748b736"></a>

---

As you can see in the screenshot, the website appears distorted on smaller devices, and some buttons are obstructed by Safari.

Thank you kindly 🙏
Best regards
NH

**Comment by ify47** [comment]
Hello Friend, i see you got more issues, i could also help you with this

**Comment by N3v1** [comment]
Thanks @ify47

**Comment by N3v1** [comment]
Hi @ify47,
How is the adaptation of the calculator going?

Thank you kindly
Best regards
NH

**Comment by ify47** [comment]
I am working on it rn, i just finished #17 issue, now I'm on this, will get you updated in no time🙏
