### ISSUE TITLE
🟡 Warning: Error with Premissions-Policy header...

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#25]
Hi everyone 👋,
If the site is launched and the console is opened, a warning appears in the JavaScript console in Chrome upon relaunch. Is this warning important or not?

Best regards
NH
<img width="1552" alt="Bildschirmfoto 2023-08-13 um 18 53 47" src="https://github.com/N3v1/Calculator/assets/129311622/c645a106-a8c6-4eb9-a594-9a049eb32eeb">

**Comment by Piyush-Deshmukh** [comment]
Hey, there!!

For this Error you can either ignore the warning or or set the `Permissions-Policy` header explicitly in your `index.html` file.

Reference : https://bobbyhadz.com/blog/error-with-permissions-policy-header-unrecognized-feature

**Comment by N3v1** [comment]
Hi @Piyush-Deshmukh, thank you for your help

Best regards
NH
