### ISSUE TITLE
🧹 UI REVAMP

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#30]
Hi @anubhav1206,
Hi @mrTSB,
Hi everyone,
I could use some help to style the calculator

## Tasks

- [ ] Create a new row for the CRL button 
- [ ] Update the style

If you have any recommendations for a new design, please let me know

Best regards
NH

**Comment by mrTSB** [comment]
I also do not like the current position of the CLR button. It could span a full row for now until we add trig, logarithms, or exponents to the row.

**Comment by N3v1** [comment]
Yes, that would be nice @mrTSB 👍🏽

**Comment by N3v1** [comment]
Thanks @mrTSB
