### ISSUE TITLE
Fix code scanning alert - Inclusion of functionality from an untrusted source

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#32]
Tracking issue for:
- [ ] https://github.com/N3v1/Calculator/security/code-scanning/2

**Comment by N3v1** [comment]
Yes @chavi362, if you want you can work on it 

Thank you kindly
Best regards
NH

**Comment by chavi362** [comment]
@N3v1 , thank you for assigning.
I would like to solve it, but first please merge my previous pull requet.
lot of thanks

**Comment by N3v1** [comment]
> @N3v1 , thank you for assigning. I would like to solve it, but first please merge my previous pull request. a lot of thanks

See #26 - there lots of other conflicts

**Comment by chavi362** [comment]
@N3v1 , please explain me the bug, the link you add brings me into 404 not found, so I don't understand the bug.

**Comment by N3v1** [comment]
@chavi36, see https://github.com/N3v1/Calculator/security/code-scanning/2 

If it doesn’t work, it’s about the script in index.html in l.37. CodeQL says:

> **Note**\
> Script loaded from content delivery >network with no integrity check.
>CodeQL

- Inclusion of functionality from an untrusted source
- Severity: [Medium](https://github.com/N3v1/Calculator/security/code-scanning?query=is%3Aopen+branch%3Amain+severity%3Amedium)
- Affected branches: main

- Tags: [security](https://github.com/N3v1/Calculator/security/code-scanning?query=tag%3Asecurity+is%3Aopen+tool%3ACodeQL)
- Weaknesses: [CWE-830](https://cwe.mitre.org/data/definitions/830.html)

### Tool
CodeQL
### Rule ID
js/functionality-from-untrusted-source
### Query
[View source](https://github.com/github/codeql/blob/6d7a75d1b945cfbd5bc5a7f71155e45bd73e676c/javascript/ql/src/Security/CWE-830/FunctionalityFromUntrustedSource.ql)

Including a resource from an untrusted source or using an untrusted channel may allow an attacker to include arbitrary code in the response. When including an external resource (for example, a script element or an iframe element) on a page, it is important to ensure that the received data is not malicious.

When including external resources, it is possible to verify that the responding server is the intended one by using an https URL. This prevents a MITM (man-in-the-middle) attack where an attacker might have been able to spoof a server response.

Even when https is used, an attacker might still compromise the server. When you use a script element, you can check for subresource integrity - that is, you can check the contents of the data received by supplying a cryptographic digest of the expected sources to the script element. The script will only load sources that match the digest and an attacker will be unable to modify the script even when the server is compromised.

Subresource integrity checking is commonly recommended when importing a fixed version of a library - for example, from a CDN (content-delivery network). Then, the fixed digest of that version of the library can easily be added to the script element's integrity attribute.

### Recommendation

When an iframe element is used to embed a page, it is important to use an https URL.

When using a script element to load a script, it is important to use an https URL and to consider checking subresource integrity.

### Example

The following example loads the jQuery library from the jQuery CDN without using https and without checking subresource integrity.

```HTML
<html>
    <head>
        <title>jQuery demo</title>
        <script src="http://code.jquery.com/jquery-3.6.0.slim.min.js" crossorigin="anonymous"></script>
    </head>
    <body>
        ...
    </body>
</html>
```
Instead, loading jQuery from the same domain using https and checking subresource integrity is recommended, as in the next example.

```HTML
<html>
    <head>
        <title>jQuery demo</title>
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    </head>
    <body>
        ...
    </body>
</html>
```

### References

MDN: [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)
Smashing Magazine: [Understanding Subresource Integrity](https://www.smashingmagazine.com/2019/04/understanding-subresource-integrity/)
Common Weakness Enumeration: [CWE-830](https://cwe.mitre.org/data/definitions/830.html).

**Comment by chavi362** [comment]
@N3v1 , I succeded to solve it!
I made a pull request, and I will be happy to see it merged
Thank you!

**Comment by N3v1** [comment]
Thank you for your work @chavi362
