### ISSUE TITLE
🟡 Design: Fix content overlapping

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#34]
### Hello everyone 👋,
I could use some help to fix the **ResultArea**. If the result is way too long, or the calculation you want to type, in the containers the content is overlapping (see screenshots below). 

I would prefer if the font got smaller as more text is displayed.

----

<img  align="left" width="200" src="https://github.com/N3v1/Calculator/assets/129311622/136d08df-c086-4ffb-8263-e4bac6a7dc44"></a>

<img align="center"  width="200" src="https://github.com/N3v1/Calculator/assets/129311622/cae9e3e8-aa0d-4d46-96a2-a3b8dd51dc45"></a>

---

Thank you kindly 👋
Best regards
NH

**Comment by ify47** [comment]
hey friend 👋, how about i help you with this issue?

**Comment by N3v1** [comment]
Yes sure, thank you @ify47

**Comment by N3v1** [comment]
Hi @ify47,
Can you please make the font size bigger? The text of the result div should be bigger. And if possible the longer the text gets the smaller its gets. Example: Apple Calculator

**Comment by N3v1** [comment]
Thank you @ify47 for you work

**Comment by N3v1** [comment]
@ify47 Do you want to work on a fix again?
