### ISSUE TITLE
✍️ Redesign: New User-Interface

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#4]
Hello everyone 👋, 
it would help me if you would help me with the redesign of the calculator.

What do you need to be able to do to help here?:

* Basic HTML knowledge
* Basic/Advanced CSS knowledge

**⚠️ Important Note: Please sync your forks to prevent merge conflicts ⚠️**

**Comment by N3v1** [comment]
Hi @anubhav1206 👋,
thank you for your help, but I get an error message in the style.css file: **'Also define the standard property "background-clip for compatibility reasons css(vendorPrefix).

Determines the background painting area.

(Chrome, Safari 3)"'.

The fault may also be on my side 🙁. Maybe I copied your changes wrong. If you still have time and desire, could you please try to fix the error (if the error message is also visible to you)? Otherwise, I would merge your PR and create a new bug in the Issue tab.
Thanks in advance 🙏 - NH

**Comment by N3v1** [comment]
Heres a screenshot of the error:
<img width="1552" alt="Bildschirmfoto 2023-08-03 um 11 21 27" src="https://github.com/N3v1/Calculator/assets/129311622/4c8f57ab-a0cf-4a92-8dd2-b352b3a4b494">

If you have questions about the translation of the error message, feel free to ask me 🙂

**Comment by anubhav1206** [comment]
> Heres a screenshot of the error: <img alt="Bildschirmfoto 2023-08-03 um 11 21 27" width="1552" src="https://user-images.githubusercontent.com/129311622/258065721-4c8f57ab-a0cf-4a92-8dd2-b352b3a4b494.png">
> 
> If you have questions about the translation of the error message, feel free to ask me 🙂

Hi @N3v1 , that seems to be a warning rather than an error. Trying to remove the warning breaks the code on my side, I would suggest just leaving it as it is.

**Comment by N3v1** [comment]
Hi @anubhav1206, 👋 
i will now merge your PR. Thanks for your help. I'm sorry that I may have caused you any inconvenience. I'm still new to web development. Thank you very much - NH
