### ISSUE TITLE
🟡 Warning: Failed to find a valid digest in the 'integrity' attribute for resource ...

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#44]
Hi everyone 👋,
I could use some help to fix those issues:

# Issue 1
If I launch the calculator and open the dev tools, I get the following warning:
```TXT
Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/mathjs/9.4.4/math.min.js' with computed SHA-512 integrity 'OZ6CXzl5JrSc9OM1lxp1OC+zt5gCTVAqy7nWwbdSUE98akAvGl/20WaIqsRUnSpBG+QBkcMkiJVfFvybZ6PtKQ=='. The resource has been blocked.
```
<img width="1552" alt="Bildschirmfoto 2023-08-25 um 13 44 12" src="https://github.com/N3v1/Calculator/assets/129311622/b4a81220-5ba8-4013-ae92-cc5511e6603d">

## Additional Infos
- Chrome v116.0.5845.96

# Issue 2
If I launch the calculator in Firefox and open the dev tools, I get the following warnings:
<img width="1392" alt="Bildschirmfoto 2023-08-25 um 21 36 18" src="https://github.com/N3v1/Calculator/assets/129311622/655ffd79-ad88-4cc1-a078-a679126bfd64">

## Additional Infos
- Firefox v. latest

# Issue 3
If I open the website on Safari I get this error in the console:
```TXT
Cannot load script https://cdnjs.cloudflare.com/ajax/libs/mathjs/9.4.4/math.min.js. Failed integrity metadata check. Content length: 644951, Expected content length: -1, Expected metadata: sha512-your-cryptographic-digest-here
```
## Additional Infos
- Safari v. ? - macOS 13.4.0

# Tasks

- [x] Issue 1 (Chrome)
- [x] Issue 2 (Firefox)
- [x] Issue 3 (Safari)

**Comment by Bolaji06** [comment]
Hi, can I work on this issue?

**Comment by N3v1** [comment]
Sure @Bolaji06

**Comment by N3v1** [comment]
Hi @Bolaji06,
how is your fix going?
Please let me know if you need any help

Best regards
NH

**Comment by Bolaji06** [comment]
> Hi @Bolaji06, how is your fix going? Please let me know if you need any help
> 
> Best regards NH

@N3v1 Sorry for the late reply. I'm done with it. Sending PR now

**Comment by Bolaji06** [comment]
> > Hi @Bolaji06, how is your fix going? Please let me know if you need any help
> > Best regards NH
> 
> @N3v1 Sorry for the late reply. I'm done with it. Sending PR now

Just sent a PR you can review it now.
Hoping to hear a feedback from you soon.

**Comment by N3v1** [comment]
Thanks @Bolaji06, everything works fine now
