### ISSUE TITLE
Config Prettier

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#49]
Hi everyone,
I need someone who can config prettier for this project

Best regards
NH

**Comment by Venkateeshh** [comment]
What do i need to do ?

**Comment by N3v1** [comment]
Hi @Venkateeshh 👋,
Config Prettier for HTML, CSS, and JS if it is possible

Best regards
NH

**Comment by Venkateeshh** [comment]
Ok i need to make to code look prettier right ?

**Comment by N3v1** [comment]
Thank you @Venkateeshh for your work on this issue
