### ISSUE TITLE
Power feature doesn't work and throws errors

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#50]
See here:

<img width="1440" alt="SCR-20230827-iong" src="https://github.com/N3v1/Calculator/assets/129311622/53cf5baf-4681-4512-a2fc-7b690b6c9d2a">

## To reproduce
1. click on the pow button (1)
2. click on a number (2)
3. click the closing bracket
4. click the evaluate button (3)
5. see error (4) - furthermore the result is not shown in the result container

**Comment by chavi362** [comment]
Yes, this is becouse you have to put which number is in pow 5
for example 2^(5)
