### ISSUE TITLE
🔴 BUG: The calculator allows writing arithmetic operator not after a number. So, an error can happen.

### ISSUE THREAD

**Issue by chavi362** [N3v1/Calculator#54]
example:
![image](https://github.com/N3v1/Calculator/assets/140444217/54c32e06-9004-4e0b-b956-23ea5a36ad11)
the user putted * not after a number.
@N3v1 , please assign it to me

**Comment by N3v1** [comment]
Thanks @chavi362

**Comment by N3v1** [comment]
If you are done with your changes, please run this command in the VScode Terminal:
```bash
npx prettier . --write
```

You may have to install node.js

**Comment by chavi362** [comment]
Can you explain me why to run this?

‫בתאריך יום ב׳, 28 באוג׳ 2023 ב-21:01 מאת ‪NH‬‏ ***@***.***
‬‏>:‬

**Comment by N3v1** [comment]
> Can you explain me why to run this? ‫בתאריך יום ב׳, 28 באוג׳ 2023 ב-21:01 מאת ‪NH‬‏ ***@***.*** ‬‏>:‬
> […](#)

The command is for the Code Formatter Prettier

**Comment by chavi362** [comment]
@N3v1 , I made a pull request for solving this issue. Please merge it.
