### ISSUE TITLE
🙋 Question: Should we update from CSS to SCSS

### ISSUE THREAD

**Issue by N3v1** [N3v1/Calculator#57]
Hi everyone,
Hi @chavi362,

I have a question, Should we update from CSS to SCSS? I've read that SCSS should be better than CSS. If so, I could use some help because I have zero experience with SCSS

Best regards
NH

**Comment by chavi362** [comment]
However, SCSS (Sassy CSS) does offer several advantages over regular CSS
that may be beneficial for your project. SCSS is a CSS preprocessor that
introduces additional features and functionality to CSS, making it easier
to write and maintain stylesheets. Some benefits of using SCSS include: 1.
Variables: SCSS allows you to define variables, which can be reused
throughout your stylesheets. This makes it easier to manage and update
colors, font sizes, and other style properties. 2. Nesting: SCSS allows you
to nest CSS selectors, making it more intuitive and readable. This can help
reduce the amount of repetitive code and improve the organization of your
stylesheets. 3. Mixins: SCSS provides mixins, which allow you to define
reusable blocks of CSS code. Mixins can be used to apply common styles to
multiple elements, reducing code duplication. 4. Inheritance: SCSS supports
inheritance, allowing you to create a base style and then extend it for
specific elements or variations. This promotes code reuse and helps
maintain consistency. 5. Importing and Partials: SCSS allows you to split
your stylesheets into smaller, modular files called partials. These
partials can be imported into a main SCSS file, making it easier to
organize and manage your styles.s I think that the advantage of
inhertitance can help us in the project becouse we can make one class for
all the botton and inheritant for the red button and for the blacks.
But, in the other hand , it may take a lot of time to change it to SCSS and
Idon't know if it's worthwhile.
 Just something I want to tell you. I have now built my first open source
project and I would really appreciate any of your contributions. If you can
please please post about it on social media and tell potential donors about
it. If you have any tips to give me on how to publish the project please
tell me.
Link to my project:https://github.com/chavi362/Icy-Tower
‫בתאריך יום ג׳, 29 באוג׳ 2023 ב-21:49 מאת ‪NH‬‏ ***@***.***
‬‏>:‬

**Comment by jiri132** [comment]
Hey @N3v1 ,

I have used SCSS for almost every project for the past 2 years, it offers many capabilities and more devloper friendly CSS writing.
While im not tat expierienced with writing really advanced SCSS I have expierience using it and unlocking the power of it.

If you want I could try and overhaul the CSS to SCSS with the compiled CSS.

Kind Regards,
JB

**Comment by N3v1** [comment]
Hi @jiri132, if you want, you can try it
