### ISSUE TITLE
🔴 BUG: F1 -> F12

### ISSUE THREAD

**Issue by jiri132** [N3v1/Calculator#61]
**Describe the bug**
> When clicking on F1 through 12 it will print these into the calculator calculation 

**To Reproduce**
> Press o of the F keys

**Expected behavior**
Nothing should happen, just ignoring the button presses

**Desktop (please complete the following information):**

- Browser [Edge]

**Comment by N3v1** [comment]
@jiri132 Can you help me fixing the issues #63 #62 #60 #61

**Comment by jiri132** [comment]
I would like to help you with fixing those!

**Comment by N3v1** [comment]
Sure @jiri132 Thanks

**Comment by jiri132** [comment]
Hey @N3v1 ,

I was coding and somewhat forgot the issues but I found it and made a change to it!

Now it will return from the event listener when it sees an F1-F12 key!
