### ISSUE TITLE
🔴 BUG: Pressing enter without calculation

### ISSUE THREAD

**Issue by jiri132** [N3v1/Calculator#63]
**Describe the bug**
> The console outputs an error when pressing the `enter` key on your keyboard

**To Reproduce**
> Press `enter`

**Expected behavior**
> Nothing unless there is a valid calculation

**Desktop (please complete the following information):**

- Browser [Edge]

**Comment by jiri132** [comment]
hey @N3v1 ,

I have sent an PR to fix this issue!

I hope you like the simple solution :P

**Comment by N3v1** [comment]
Thanks @jiri132
