### ISSUE TITLE
🔴 BUG: % not working properly

### ISSUE THREAD

**Issue by jiri132** [N3v1/Calculator#7]
**Describe the bug**
Well, the % doesn't behave as the normal calculators have the % function behave, 

** Idea what you can do to prevent**
you can have 2 types of % behaviors based on input after the % but that would make you probably re-write the whole calculator system and end to implement BOS-MAS in order of breaking down you're instructions and make a correct  numeric operation to execute

**To Reproduce**
1. Go to 'the web server'
2. Click on '8 , * , 1,0, %'
3. Scroll down to 'see the console of browser'

**Expected behavior**
8 * 10% = 0.8 
this is because 10% = 0.1 in numeric form 
so basically this translates to 8 * 0.1 
because it takes 8 * 10% and just parses it to javascript numeric operation it will return an error because it does not do the 10 % through something, like 10 % 1 = 0 because the 1 can fully go into the 10 so there are no leftovers

 
**Screenshots**
![image](https://github.com/N3v1/Calculator/assets/76393975/07b2e5d0-58b7-4e35-96dd-f88c4d930116)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Browser [edge]
 - Version [idk]

**Additional context**
javascript/computer operations of % are always the leftover form dividing

**Comment by jiri132** [comment]
I would like to help you with this but as I said you will probably have to write a BOS-MAS order for you're calculator to break down the whole calculation and that way it is also easier to implement #3

**Comment by N3v1** [comment]
Hi @jiri132 👋,
Thank you for this Bug report.
If I'm honest, what is 'BOS-MAS'? I've never heard of it. 🙁
How can I do that? 

I really appreciate your extraordinary help jiri132.

Thank you kindly 🙏
Best regards,
NH

**Comment by jiri132** [comment]
Hey @N3v1 ,

Sorry I meant BOD-MAS 
a small mistake of mine! 

It is the way how we define our math laws like 
1. ()
2. power, sin,cos,tan,root
3. * ,/
4. +, -
 
And instead of doing `eval()` 

you could also create an algorithm to sort out the ways how it should perform these actions in that way you can precompute 10% to 0.1 so that you can type: `8 * 10%` it will get run through BOD-MAS way of in what order it would get looked at the new calculation of numeric values:  `8 * 0.1` thus giving the result needed

This is one way to implement the usage of the start of you're understanding of BOD-MAS in our computing laws!

Kind regards,
JB

**Comment by N3v1** [comment]
Hi @jiri132 👋,
Thank you for your explanation. I will try to fix the problem in the next few weeks.
If I needed help I would mention you if that's ok with you.

Thank you kindly 🙏
Best regards,
NH

**Comment by N3v1** [comment]
Hi @jiri132 👋,
the error comes because you didn't type anything after the percent sign. I don't have the 404 error at the beginning.
I'm sorry if I misunderstand you but the percentage calculation works.

---

Example 10% 100 = 10
<img width="1552" alt="Bildschirmfoto 2023-08-05 um 00 07 44" src="https://github.com/N3v1/Calculator/assets/129311622/3b6750ee-bbc0-4cdc-b697-c3f9e68f2fb0">

Example 10 % missing Number
<img width="1552" alt="Bildschirmfoto 2023-08-05 um 00 07 55" src="https://github.com/N3v1/Calculator/assets/129311622/b24edf21-9cc7-46d1-8218-012a5c94ca43">

**Comment by N3v1** [comment]
In addition, the calculator respects the BODMAS and/or the PEDMAS rule:
**Example:**

---

Beispiel:
20 - 5 * 3 = 5   
20 - 5 * 3 != 45 
<img width="1552" alt="Bildschirmfoto 2023-08-05 um 00 15 55" src="https://github.com/N3v1/Calculator/assets/129311622/a0065354-7e30-4750-af80-624d8b7a6d2b">

---

But, if you have any suggestions on how I can change the code, it would be helpful if you clone the repo, create a new branch, make the changes and send them to me via a pull request. Only if you have time and desire.

Thank you kindly 🙏
Best regards,
NH

**Comment by jiri132** [comment]
> Hi @jiri132 👋, the error comes because you didn't type anything after the percent sign. I don't have the 404 error at the beginning. I'm sorry if I misunderstand you but the percentage calculation works.
> 
> Example 10% 100 = 10 <img alt="Bildschirmfoto 2023-08-05 um 00 07 44" width="1552" src="https://user-images.githubusercontent.com/129311622/258539386-3b6750ee-bbc0-4cdc-b697-c3f9e68f2fb0.png">
> 
> Example 10 % missing Number <img alt="Bildschirmfoto 2023-08-05 um 00 07 55" width="1552" src="https://user-images.githubusercontent.com/129311622/258539476-b24edf21-9cc7-46d1-8218-012a5c94ca43.png">

Hey @N3v1 

That is right I didn't put anything behind the %, in normal calculators you don't do the % numeric operation like in code to use it to see what the left overs are from dividing.

So normally if you do 100% it means that it that you had a it all for example in real life

income: `10 000 `
federal tax: `51%`
the n the calculation is `10 000 * 51%`
in this case the outcome is: `5 100`
so how did we come with the `5 100`? well it is not that hard to understand the % way of representing this is a way to make it simpler to look at the fraction, normally this would get broken down to `(% value) / 100`
so for example: `(51%) / 100` -> `51/100` - > `0,51` 

So if you look back again at the calculation you can represent it also as `10 000 * 0.51` -> `5 100` 
it is thee same outcome but then with a fractional display.

the current use of `%` isn't wrong if you aim the calculator to work just like code, but I think you wanted  an calculator that is applicable to 'normal' calculators if I am not mistaken :D

I hope this cleared up any of the confusion that I may brought you about the the error / bug
Kind Greetings,
JB

**Comment by N3v1** [comment]
Hi @jiri132 ,
I got it now. I'm trying to revamp the calculator somehow

Thank you kindly 🙏
Best regards,
NH

**Comment by jiri132** [comment]
Hi @N3v1 , 

I have found a way to keep the code how it is and still introduce mathematical functions and manipulate the variables so that you don't have to write BOD-MAS yourself!
Just check my recent pull request and it has all information in it to hopefully let you understand it how to transform the calculation and append the correct values each time that we would need in normal `(), * /, + -` way of computing

Kind regards,
JB

**Comment by N3v1** [comment]
Hello @jiri132, would you mind taking a look at issue **(#19)**?

**Comment by N3v1** [comment]
I urgently need your response ASAP. @jiri132
