### ISSUE TITLE
🌟Feature: See calculation that made up result

### ISSUE THREAD

**Issue by jiri132** [N3v1/Calculator#8]
**Is your feature request related to a problem? Please describe.**
When you enter a calculation for example 10 * 1242 and you get the output I don't know what I have put into the calculator to get that result, 

**Describe the solution you'd like**
that the area is a 2 fielded area where the text from the result gets returned to when you press the = button, 
it will be also cleared when you press `delete`, or when you put in a new calculation

**Additional context**
I don't really have any

**Comment by N3v1** [comment]
Hey @jiri132 👋,
It would be nice if you help me to do a PR review. Only if you have time and desire. It's about the PR from **DoonOnthon**. He made changes in the index.js file where you made changes. It would help me a lot if you could look at the changes and see if the changes you made aren't gone again

Thank you kindly 🙏,
Best regards
NH

**Comment by N3v1** [comment]
Here is the link to the PR https://github.com/N3v1/Calculator/pull/12

**Comment by N3v1** [comment]
Hey @jiri132 👋,
I could use some help checking this [**PR**](https://github.com/N3v1/Calculator/pull/12). I don't know if his changes could break the % bug fix you did.
